<?php
/**
 * Configuration for the payments page.
 * Copy this file to config.php and fill in your credentials.
 */

define('DB_HOST', 'localhost');
define('DB_NAME', 'futsal_bot');
define('DB_USER', 'futsal_bot');
define('DB_PASS', 'your_password_here');

/**
 * Link signing needs no key here: each chat gets its own, generated by the
 * bots and stored in Chats.page_secret, and this page checks a link against
 * the keys of the chats the event belongs to. Nothing to configure — links
 * from one group simply do not open another group's event.
 */

/**
 * Fallback label for the kitty. Each chat records its own currency with the
 * amount (/event_bank 5200 ₸), so this is only used for entries made before
 * that existed.
 */
define('BANK_CURRENCY', '₽');

/** Default window, in weeks, for the duty table. */
define('DUTY_WEEKS_DEFAULT', 4);
